version: "3.7"

services:
  database:
    image: postgres
    container_name: bolao-app-api-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=bolao-app-db
      - POSTGRES_PASSWORD=bolao-app-db-pass
      - POSTGRES_DB=bolao-app-db
    volumes:
      - pgdata:/data/postgres


  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    container_name: bolao-app-api-redis



  app:
    build: .
    container_name: bolao-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
    env_file:
      - .env


volumes:
  pgdata:
    driver: local